wifi.setmode(wifi.STATION)
wifi.sleeptype(wifi.MODEM_SLEEP)
wifi.sta.config(SSID,PASSWORD)
-- wifi.sta.setip({ip=IP,netmask="255.255.255.0",gateway=GETEWAYIP})
wifi.sta.connect()
-- net.dns.setdnsserver("8.8.8.8", 1)
